packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@t3-oss/env-core": "^0.13.10"
  "effect": "^3.19.16"
  "zod": "^4.3.6"
  "lint-staged": "^16.2.7"
  "@dotenvx/dotenvx": "^1.52.0"
  "typescript": "5.9.2"
  "@types/node": "^25.2.3"
  "@types/react": "^19.2.13"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^5.1.4"
  "vite": "^7.3.1"
  "vite-tsconfig-paths": "^6.1.0"
  "react": "^19.2.4"
  "react-dom": "^19.2.4"
  "tailwindcss": "^4.1.18"
  "@tanstack/react-query": "^5.90.21"
  "@tanstack/react-router": "^1.159.5"
  "@tanstack/react-router-devtools": "^1.159.5"
  "@tanstack/react-router-ssr-query": "^1.159.5"
  "@tanstack/react-start": "^1.159.5"
  "@tanstack/react-query-devtools": "^5.91.3"
  "@tailwindcss/vite": "^4.1.18"
  "@biomejs/biome": "2.3.13"
  "@tailwindcss/cli": "^4.1.18"
  "sonner": "^2.0.7"
  "resend": "^6.9.2"

catalogMode: prefer
