/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as authenticatedProfileRouteImport } from './routes/(authenticated)/profile'
import { Route as authenticatedCreateNewWorkspaceRouteImport } from './routes/(authenticated)/create-new-workspace'
import { Route as authenticatedWorkspacesIndexRouteImport } from './routes/(authenticated)/workspaces/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedWorkspacesWorkspaceIdRouteRouteImport } from './routes/(authenticated)/workspaces/$workspaceId/route'
import { Route as authenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/(authenticated)/workspaces/$workspaceId/index'
import { Route as authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport } from './routes/(authenticated)/workspaces/$workspaceId/projects/$projectId/route'
import { Route as authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/(authenticated)/workspaces/$workspaceId/projects/$projectId/index'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedProfileRoute = authenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCreateNewWorkspaceRoute =
  authenticatedCreateNewWorkspaceRouteImport.update({
    id: '/create-new-workspace',
    path: '/create-new-workspace',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedWorkspacesIndexRoute =
  authenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedWorkspacesWorkspaceIdRouteRoute =
  authenticatedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedWorkspacesWorkspaceIdIndexRoute =
  authenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute =
  authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => authenticatedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-new-workspace': typeof authenticatedCreateNewWorkspaceRoute
  '/profile': typeof authenticatedProfileRoute
  '/sign-in/': typeof SignInIndexRoute
  '/workspaces/$workspaceId': typeof authenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/': typeof authenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/': typeof authenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
  '/workspaces/$workspaceId/projects/$projectId/': typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-new-workspace': typeof authenticatedCreateNewWorkspaceRoute
  '/profile': typeof authenticatedProfileRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces': typeof authenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof authenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/create-new-workspace': typeof authenticatedCreateNewWorkspaceRoute
  '/(authenticated)/profile': typeof authenticatedProfileRoute
  '/sign-in/': typeof SignInIndexRoute
  '/(authenticated)/workspaces/$workspaceId': typeof authenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/workspaces/': typeof authenticatedWorkspacesIndexRoute
  '/(authenticated)/workspaces/$workspaceId/': typeof authenticatedWorkspacesWorkspaceIdIndexRoute
  '/(authenticated)/workspaces/$workspaceId/projects/$projectId': typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
  '/(authenticated)/workspaces/$workspaceId/projects/$projectId/': typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-new-workspace'
    | '/profile'
    | '/sign-in/'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/workspaces/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-new-workspace'
    | '/profile'
    | '/sign-in'
    | '/api/auth/$'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(authenticated)/create-new-workspace'
    | '/(authenticated)/profile'
    | '/sign-in/'
    | '/(authenticated)/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/(authenticated)/workspaces/'
    | '/(authenticated)/workspaces/$workspaceId/'
    | '/(authenticated)/workspaces/$workspaceId/projects/$projectId'
    | '/(authenticated)/workspaces/$workspaceId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/profile': {
      id: '/(authenticated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/create-new-workspace': {
      id: '/(authenticated)/create-new-workspace'
      path: '/create-new-workspace'
      fullPath: '/create-new-workspace'
      preLoaderRoute: typeof authenticatedCreateNewWorkspaceRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/workspaces/': {
      id: '/(authenticated)/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof authenticatedWorkspacesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/workspaces/$workspaceId': {
      id: '/(authenticated)/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof authenticatedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/workspaces/$workspaceId/': {
      id: '/(authenticated)/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof authenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof authenticatedWorkspacesWorkspaceIdRouteRoute
    }
    '/(authenticated)/workspaces/$workspaceId/projects/$projectId': {
      id: '/(authenticated)/workspaces/$workspaceId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof authenticatedWorkspacesWorkspaceIdRouteRoute
    }
    '/(authenticated)/workspaces/$workspaceId/projects/$projectId/': {
      id: '/(authenticated)/workspaces/$workspaceId/projects/$projectId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute
    }
  }
}

interface authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren {
  authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}

const authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren: authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren =
  {
    authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
      authenticatedWorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
  }

const authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren =
  authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute._addFileChildren(
    authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren,
  )

interface authenticatedWorkspacesWorkspaceIdRouteRouteChildren {
  authenticatedWorkspacesWorkspaceIdIndexRoute: typeof authenticatedWorkspacesWorkspaceIdIndexRoute
  authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute: typeof authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
}

const authenticatedWorkspacesWorkspaceIdRouteRouteChildren: authenticatedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    authenticatedWorkspacesWorkspaceIdIndexRoute:
      authenticatedWorkspacesWorkspaceIdIndexRoute,
    authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRoute:
      authenticatedWorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren,
  }

const authenticatedWorkspacesWorkspaceIdRouteRouteWithChildren =
  authenticatedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    authenticatedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedCreateNewWorkspaceRoute: typeof authenticatedCreateNewWorkspaceRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
  authenticatedWorkspacesWorkspaceIdRouteRoute: typeof authenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  authenticatedWorkspacesIndexRoute: typeof authenticatedWorkspacesIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCreateNewWorkspaceRoute: authenticatedCreateNewWorkspaceRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
  authenticatedWorkspacesWorkspaceIdRouteRoute:
    authenticatedWorkspacesWorkspaceIdRouteRouteWithChildren,
  authenticatedWorkspacesIndexRoute: authenticatedWorkspacesIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
