import type { Query, QueryClient } from "@tanstack/react-query";

export type Prettify<Type> = Type extends () => unknown
  ? Type
  : Extract<
      {
        [Key in keyof Type]: Type[Key];
      },
      Type
    >;

export type Merge<Object1, Object2> = Prettify<
  Omit<Object1, keyof Object2> & Object2
>;

export type GenerateQueryKey<T extends string> = (
  ...args: unknown[]
) => [T, ...unknown[]];

export type GenerateQueryKeyWithArgs<T extends string, U extends unknown[]> = (
  ...args: U[]
) => [T, ...U[]];

export type GenerateQueryKeyFunction<
  T extends string,
  U extends unknown[] = unknown[],
> = GenerateQueryKey<T> | GenerateQueryKeyWithArgs<T, U>;

/**
 * Factory for creating and managing query keys with optional annotations.
 *
 * @template Annotations - Shape of the annotation objects associated with each query key.
 * @template TKeysObject - Record of generated query key functions.
 *
 * @example
 * ```ts
 * import { QueryClient } from "@tanstack/react-query";
 * import QueryKeyFactory from "./factory";
 *
 * // Create a React Query client
 * const queryClient = new QueryClient();
 *
 * // Initialise the factory with a specific annotation shape
 * type MyAnnotations = { role: string };
 * const factory = new QueryKeyFactory<MyAnnotations>(queryClient);
 *
 * // Register a simple query key with annotations
 * factory
 *   .createQueryKey("users", { role: "admin" })
 *   // Register a query key that accepts arguments
 *   .createQueryKeyWithArgs("posts")<[{ id: number }]>()
 *   // Add additional annotations later
 *   .annotateQuery("posts", { role: "editor" });
 * ```
 */
export default class QueryKeyFactory<
  // biome-ignore lint/complexity/noBannedTypes: this is used in the docs
  Annotations extends Record<string, unknown> = {},
  // biome-ignore lint/complexity/noBannedTypes: this is used in the docs
  TKeysObject extends Record<string, GenerateQueryKeyFunction<string>> = {},
> {
  /**
   * React Query client used for invalidating and resetting queries.
   *
   * This client is injected through the constructor and provides the
   * functionality for `invalidateQueries`, `resetQueries`, and internal
   * query filtering. It enables the factory to directly interact with the
   * React Query cache, ensuring that query operations are scoped to the
   * keys generated by this factory.
   */
  private queryClient: QueryClient;

  /** Record that stores the generated query key functions. */
  private factory: TKeysObject;

  /**
   * Record that maps each query key to its partial annotation set.
   *
   * @remarks
   * The keys of this record correspond to the keys of `TKeysObject`. Each entry
   * holds a partial set of annotations, allowing incremental annotation updates.
   */
  private annotationsRecord: Record<keyof TKeysObject, Partial<Annotations>>;

  /**
   * Creates a new `QueryKeyFactory` instance.
   *
   * @param queryClient - The `QueryClient` instance from React Query.
   */
  constructor(queryClient: QueryClient) {
    this.queryClient = queryClient;
    this.factory = {} as TKeysObject;
    this.annotationsRecord = {} as Record<
      keyof TKeysObject,
      Partial<Annotations>
    >;
  }

  /**
   * Registers a simple query key (without additional arguments) and optionally
   * associates annotations with it.
   *
   * @param key - The string identifier for the query key.
   * @param annotation - Optional annotations to associate with the key.
   * @returns The factory instance, typed with the new query key added.
   *
   * @example
   * ```ts
   * // Register a query key called "users" with a role annotation
   * factory.createQueryKey("users", { role: "admin" });
   *
   * // The generated function can be used directly:
   * const userKey = factory.queries.users(); // ["users"]
   * ```
   */
  createQueryKey<Key extends string>(
    key: Key,
    annotation?: Partial<Annotations>
  ) {
    this.factory = {
      ...this.factory,
      [key]: this.generateQueryKey(key),
    };

    this.annotationsRecord[key] = {
      ...this.annotationsRecord[key],
      ...annotation,
    };

    return this as unknown as QueryKeyFactory<
      Annotations,
      Merge<TKeysObject, { [k in Key]: GenerateQueryKey<Key> }>
    >;
  }

  /**
   * Registers a query key that expects additional arguments and optionally
   * associates annotations with it.
   *
   * @param key - The string identifier for the query key.
   * @param annotations - Optional annotations to associate with the key.
   * @returns A higher‑order function that, when called with the argument tuple type,
   *          returns the factory instance typed with the new query key added.
   *
   * @example
   * ```ts
   * // Register a query key "post" that expects an object containing an id
   * const factoryWithPost = factory
   *   .createQueryKeyWithArgs("post")<[{ id: number }]>()
   *   .annotateQuery("post", { role: "editor" });
   *
   * // Use the generated function:
   * const postKey = factoryWithPost.queries.post({ id: 42 }); // ["post", { id: 42 }]
   * ```
   */
  createQueryKeyWithArgs<Key extends string>(
    key: Key,
    annotations?: Partial<Annotations>
  ) {
    return <U extends unknown[]>() => {
      this.factory = {
        ...this.factory,
        [key]: this.generateQueryKeyWithArgs<Key, U>(key),
      };

      this.annotationsRecord[key] = {
        ...this.annotationsRecord[key],
        ...annotations,
      };

      return this as unknown as QueryKeyFactory<
        Annotations,
        Merge<TKeysObject, { [k in Key]: GenerateQueryKeyWithArgs<Key, U> }>
      >;
    };
  }

  /**
   * Generates a query key function that accepts any number of arguments.
   *
   * @param key - The base string for the query key.
   * @returns A function that composes the base key with supplied arguments.
   */
  private generateQueryKey =
    <Key extends string>(key: Key): GenerateQueryKey<Key> =>
    (...args) => [key, ...args];

  /**
   * Generates a query key function that expects a specific tuple of arguments.
   *
   * @param key - The base string for the query key.
   * @returns A function that composes the base key with arguments of type `U`.
   */
  private generateQueryKeyWithArgs =
    <Key extends string, U extends unknown[]>(
      key: Key
    ): GenerateQueryKeyWithArgs<Key, U> =>
    (...args) => [key, ...args];

  /**
   * Adds or merges annotations for an existing query key.
   *
   * @param key - The query key to annotate.
   * @param annotation - The annotation data to merge.
   * @returns The current `QueryKeyFactory` instance.
   *
   * @example
   * ```ts
   * // Add a role annotation to an already‑registered query key
   * factory.annotateQuery("users", { role: "viewer" });
   * ```
   */
  annotateQueryKey(key: keyof TKeysObject, annotation: Partial<Annotations>) {
    this.annotationsRecord[key] = {
      ...this.annotationsRecord[key],
      ...annotation,
    };

    return this;
  }

  /** Returns the current record of query key functions. */
  get keys() {
    return this.factory;
  }

  /**
   * Retrieves the generated query key for a given key.
   *
   * @param key - The key whose query function should be retrieved.
   * @returns The result of invoking the stored query key function.
   * @throws If the key does not exist in the factory.
   *
   * @example
   * ```ts
   * // Assuming "users" was registered earlier
   * const key = factory.getQuery("users"); // ["users"]
   * ```
   */
  getQueryKeyFn<T extends keyof TKeysObject>(key: T): TKeysObject[T] {
    const queryKeyFn = this.factory[key];

    if (!queryKeyFn) {
      throw new Error(`Query key ${key.toString()} not found`);
    }

    return queryKeyFn;
  }

  /**
   * Retrieves the base part (first element) of each supplied query key.
   *
   * @param keys - One or more keys to retrieve the base values for.
   * @returns An array of base values for the provided keys.
   *
   * @example
   * ```ts
   * const bases = factory.getQueryKeys("users", "posts"); // ["users", "posts"]
   * ```
   */
  getQueryKeys(...keys: (keyof TKeysObject)[]) {
    return keys.map((key) => this.factory[key]?.().at(0));
  }

  /**
   * Fetches the annotations associated with a specific query key.
   *
   * @param key - The query key whose annotations should be returned.
   * @returns The partial annotation object for the key.
   *
   * @example
   * ```ts
   * const annotations = factory.getQueryKeyAnnotations("users");
   * // { role: "admin" }
   * ```
   */
  getQueryKeyAnnotations(key: keyof TKeysObject) {
    return this.annotationsRecord[key];
  }

  /**
   * Creates a predicate function used by React Query to filter queries based on
   * their base key.
   *
   * @param keys - Keys to match against query keys.
   * @returns A predicate suitable for `QueryClient` methods.
   */
  private queryFiltering(keys: (keyof TKeysObject)[]) {
    return (query: Query<unknown>) =>
      this.getQueryKeys(...keys).includes(query.queryKey.at(0));
  }

  /**
   * Invalidates all queries that match the specified keys.
   *
   * @param keys - The query keys to invalidate.
   *
   * @example
   * ```ts
   * // Invalidate all "users" queries
   * factory.invalidateQueries("users");
   * ```
   */
  invalidateQueries(...keys: (keyof TKeysObject)[]) {
    this.queryClient.invalidateQueries({
      predicate: this.queryFiltering(keys),
    });
  }

  /**
   * Resets (removes) all queries that match the specified keys.
   *
   * @param keys - The query keys to reset.
   *
   * @example
   * ```ts
   * // Reset all "posts" queries from the cache
   * factory.resetQueries("posts");
   * ```
   */
  resetQueries(...keys: (keyof TKeysObject)[]) {
    this.queryClient.resetQueries({
      predicate: this.queryFiltering(keys),
    });
  }

  /**
   * Retrieves all query keys whose stored annotations match the provided
   * partial annotation filter.
   *
   * @param annotations - Partial annotation object to match against.
   * @returns An array of matching query key names.
   *
   * @example
   * ```ts
   * // Find all keys annotated with role: "admin"
   * const adminKeys = factory.getQueryKeysFromAnnotation({ role: "admin" });
   * ```
   */
  private getQueryKeysFromAnnotation(annotations: Partial<Annotations>) {
    const keys = Object.keys(this.annotationsRecord).filter((key) => {
      const annotation = this.annotationsRecord[key as keyof TKeysObject];
      return Object.keys(annotations).every(
        (annotationKey) =>
          annotation[annotationKey] === annotations[annotationKey]
      );
    });
    return keys;
  }

  /**
   * Invalidates all queries whose annotations match the supplied filter.
   *
   * @param annotations - Partial annotation filter.
   *
   * @example
   * ```ts
   * // Invalidate every query whose role annotation is "editor"
   * factory.invalidateQueryByAnnotations({ role: "editor" });
   * ```
   */
  invalidateQueryByAnnotations(annotations: Partial<Annotations>) {
    this.invalidateQueries(...this.getQueryKeysFromAnnotation(annotations));
  }

  /**
   * Resets all queries whose annotations match the supplied filter.
   *
   * @param annotation - Partial annotation filter.
   *
   * @example
   * ```ts
   * // Reset every query with a "viewer" role annotation
   * factory.resetQueryByAnnotations({ role: "viewer" });
   * ```
   */
  resetQueryByAnnotations(annotation: Partial<Annotations>) {
    this.resetQueries(...this.getQueryKeysFromAnnotation(annotation));
  }
}
